### ISSUE TITLE
关于跨域访问的这个地方代码是不是手误

### ISSUE THREAD

**Issue by bhdweb** [lord-of-code/loc-framework#6]
`@Configuration
@ConditionalOnWebApplication(type = Type.SERVLET)
@EnableConfigurationProperties(LocSpringMvcCorsProperties.class)
public class LocSpringMvcAutoConfiguration {

  @Bean
  @ConditionalOnClass(CorsFilter.class)
  @ConditionalOnProperty(value = "loc.web.springmvc.cors.enabled")
  public Filter corsFilter(LocSpringMvcCorsProperties locSpringMvcCorsProperties) {
    UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
    source.registerCorsConfiguration(
        Optional.ofNullable(locSpringMvcCorsProperties.getPath()).orElse("/**"),
        buildConfig(locSpringMvcCorsProperties));
    return new CorsFilter(source);
  }

  private CorsConfiguration buildConfig(LocSpringMvcCorsProperties locSpringMvcCorsProperties) {
    CorsConfiguration corsConfiguration = new CorsConfiguration();
    Optional.ofNullable(locSpringMvcCorsProperties.getAllowOrigins())
        .ifPresent(origins -> origins.forEach(corsConfiguration::addAllowedOrigin));
    Optional.ofNullable(locSpringMvcCorsProperties.getAllowHeaders())
        .ifPresent(headers -> headers.forEach(corsConfiguration::addAllowedHeader));
    Optional.ofNullable(locSpringMvcCorsProperties.getAllowOrigins())
        .ifPresent(methods -> methods.forEach(corsConfiguration::addAllowedMethod));
    Optional.ofNullable(locSpringMvcCorsProperties.getAllowExposeHeaders())
        .ifPresent(headers -> headers.forEach(corsConfiguration::addExposedHeader));
    return corsConfiguration;
  }`
两次使用了locSpringMvcCorsProperties.getAllowOrigins()，最后一次应该是locSpringMvcCorsProperties.getAllowMethods()

**Comment by dragontree101** [comment]
多谢， 貌似 后面的那个 不应该是 `getAllowOrigins `, 而是 `getAllowMethods`

**Comment by dragontree101** [comment]
#
